name: 'Build, Test, and Publish PowerShell Module'
on: [push]
env:
  MODULE_NAME: 'KeepAlive'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: russellds/pwsh-module-build@v0

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: russellds/pwsh-module-test@v0
        with:
          moduleName: ${{ env.MODULE_NAME }}

  publish:
    runs-on: windows-latest
    needs: test
    steps:
      - uses: russellds/pwsh-module-publish@v0
        with:
          moduleName: ${{ env.MODULE_NAME }}
          nuGetApiKey: ${{ secrets.PS_GALLERY_API_KEY }}
