name: 'Build, Test, and Publish PowerShell Module'
on: [push]
env:
  MODULE_NAME: 'KeepAlive'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: russellds/pwsh-module-build@v0
      id: pwshModuleBuild

    - name: WriteHost
      shell: pwsh
      run: |
        Write-Host "PreReleaseTag: ${{ steps.pwshModuleBuild.outputs.preReleaseTag }}"

    outputs:
      preReleaseTag: ${{ steps.pwshModuleBuild.outputs.preReleaseTag }}

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: russellds/pwsh-module-test@v0
        with:
          moduleName: ${{ env.MODULE_NAME }}

  publishPreview:
    runs-on: windows-latest
    needs: test
    environment:
      name: preview
    steps:
      - name: WriteHost
        shell: pwsh
        run: |
          Write-Host "PreReleaseTag: ${{ needs.pwshModuleBuild.outputs.preReleaseTag }}"

      # - uses: russellds/pwsh-module-publish@v0
      #   if: ${{ needs.pwshModuleBuild.outputs.preReleaseTag == 'preview' }}
      #   with:
      #     moduleName: ${{ env.MODULE_NAME }}
      #     nuGetApiKey: ${{ secrets.PS_GALLERY_API_KEY }}
      #     testGallery: 'True'

  publishProd:
    runs-on: windows-latest
    needs: [build, test]
    environment:
      name: prod
    steps:
      - name: WriteHost
        shell: pwsh
        run: |
          Write-Host "PreReleaseTag: ${{ needs.pwshModuleBuild.outputs.preReleaseTag }}"

      # - uses: russellds/pwsh-module-publish@v0
      #   if: ${{ needs.pwshModuleBuild.outputs.preReleaseTag == '' }}
      #   with:
      #     moduleName: ${{ env.MODULE_NAME }}
      #     nuGetApiKey: ${{ secrets.PS_GALLERY_API_KEY }}
